permissionset 80100 EasyTilesSUPER
{
    Assignable = true;
    Caption = 'EasyTiles SUPER permission';
    Permissions = tabledata "Easy Tile Buffer" = RIMD,
        tabledata "Easy Tile Group" = RIMD,
        tabledata "Easy Tile Group Assignment" = RIMD,
        tabledata "Easy Tile Group Line" = RIMD,
        tabledata "Easy Tile SVG Header" = RIMD,
        tabledata "Easy Tile SVG Line" = RIMD,
        tabledata "Easy Tile SVG Main Style Line" = RIMD,
        tabledata "Easy Tile SVG Tag" = RIMD,
        tabledata "Easy Tile Table Filter" = RIMD,
        table "Easy Tile Buffer" = X,
        table "Easy Tile Group" = X,
        table "Easy Tile Group Assignment" = X,
        table "Easy Tile Group Line" = X,
        table "Easy Tile SVG Header" = X,
        table "Easy Tile SVG Line" = X,
        table "Easy Tile SVG Main Style Line" = X,
        table "Easy Tile SVG Tag" = X,
        table "Easy Tile Table Filter" = X,
        codeunit "Easy Tile Functions" = X,
        codeunit "Easy Tile Open Group" = X,
        codeunit "Easy Tile SVG Management" = X,
        codeunit "Easy Tiles Filter Mgt.SG" = X,
        page "Easy Tile Activities" = X,
        page "Easy Tile colour Picker" = X,
        page "Easy Tile Group Assignments" = X,
        page "Easy Tile Group Lines" = X,
        page "Easy Tile Groups" = X,
        page "Easy Tile Object Lookup" = X,
        page "Easy Tile Preview" = X,
        page "Easy Tile Select Key" = X,
        page "Easy Tile Setup Card" = X,
        page "Easy Tile SVG Definition" = X,
        page "Easy Tile SVG List" = X,
        page "Easy Tile SVG Main St. SubPage" = X,
        page "Easy Tile SVG SubPage" = X,
        page "Easy Tile SVG Tag Selector" = X,
        page "Easy Tile Table Filter" = X;
}